name: bcos-executor GitHub Actions
on:
  push:
    paths-ignore:
      - "docs/**"
      - "Changelog.md"
      - "README.md"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "Changelog.md"
      - "README.md"
  release:
    types: [published, created, edited]
env:
  CCACHE_DIR: ${{ github.workspace }}/ccache

jobs:
  build_with_clang:
    name: build_with_clang
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5
      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            /home/runner/.hunter
            /Users/runner/.hunter
            /home/runner/.hunter/_Base/Download/
            /Users/runner/.hunter/_Base/Download/
            deps/src
            ccache
          key: hunter-clang-v8-notest-${{ runner.temp }}-${{ github.base_ref }}-${{ hashFiles('.github/workflows/workflow.yml') }}
          restore-keys: |
            hunter-clang-v8-notest-${{ runner.temp }}-${{ github.base_ref }}-${{ hashFiles('.github/workflows/workflow.yml') }}
            hunter-clang-v8-notest-${{ runner.temp }}-${{ github.base_ref }}-
            hunter-clang-v8-notest-${{ runner.temp }}-
      - name: install macOS dependencies
        if: runner.os == 'macOS'
        run: brew install ccache
      - name: install Ubuntu dependencies
        if: runner.os == 'Linux'
        run: sudo apt install -y git curl build-essential clang cmake ccache
      - name: configure
        if: runner.os == 'macOS'
        run: export SDKROOT=$(xcrun --sdk macosx --show-sdk-path) && CC=/usr/bin/clang CXX=/usr/bin/clang++ cmake . -DTESTS=ON
      - name: install rust language
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-06-17
          override: true
      - name: Linux configure
        if: runner.os == 'Linux'
        run: CC=/usr/bin/clang CXX=/usr/bin/clang++ cmake . -DTESTS=ON
      - name: check commit
        if: ${{ runner.os == 'Linux' && github.base_ref != 'master' && github.event_name == 'pull_request' }}
        run: bash cmake/scripts/shell/check-commit.sh 3000 "https://api.github.com/repos/FISCO-BCOS/bcos-executor"
      - name: compile
        run: make -j2
      - name: run test
        run: CTEST_OUTPUT_ON_FAILURE=TRUE make test

  ubuntu20_04_build_with_gcc:
    name: build20_04_with_gcc
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5
      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            /home/runner/.hunter
            /home/runner/.hunter/_Base/Download/
            deps/src
            ccache
          key: hunter-gcc-v8-notest-${{ runner.temp }}-${{ github.base_ref }}-${{ hashFiles('.github/workflows/workflow.yml') }}
          restore-keys: |
            hunter-gcc-v8-notest-${{ runner.temp }}-${{ github.base_ref }}-${{ hashFiles('.github/workflows/workflow.yml') }}
            hunter-gcc-v8-notest-${{ runner.temp }}-${{ github.base_ref }}-
            hunter-gcc-v8-notest-${{ runner.temp }}-
      - name: install Ubuntu dependencies
        run: sudo apt install -y git curl build-essential cmake ccache lcov
      - name: install rust language
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-06-17
          override: true
      - name: configure
        run: cmake . -DTESTS=ON  -DCOVERAGE=ON
      - name: compile
        run: make -j2
      - name: run test
        run: CTEST_OUTPUT_ON_FAILURE=TRUE make test
      - name: generate coverage
        run: make coverage
      - name: upload code coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.info
          name: code coverage
          fail_ci_if_error: true
          gcov_path_exclude: deps/

  ubuntu18_04_build_with_gcc:
    name: ubuntu18_04_build_with_gcc
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5
      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            /home/runner/.hunter
            /home/runner/.hunter/_Base/Download/
            deps/src
            ccache
          key: hunter-ubuntu-v8-notest-${{ runner.temp }}-${{ github.base_ref }}-${{ hashFiles('.github/workflows/workflow.yml') }}
          restore-keys: |
            hunter-ubuntu-v8-notest-${{ runner.temp }}-${{ github.base_ref }}-${{ hashFiles('.github/workflows/workflow.yml') }}
            hunter-ubuntu-v8-notest-${{ runner.temp }}-${{ github.base_ref }}-
            hunter-ubuntu-v8-notest-${{ runner.temp }}-
      - name: install Ubuntu dependencies
        run: sudo apt install -y git curl build-essential cmake ccache
      - name: install rust language
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-06-17
          override: true
      - name: configure
        run: cmake . -DTESTS=ON -DDEBUG=ON
      - name: compile
        run: make -j2
      - name: run test
        run: CTEST_OUTPUT_ON_FAILURE=TRUE make test

  build_centos_with_gcc:
    name: build_centos_with_gcc
    runs-on: ubuntu-latest
    container:
      image: docker.io/centos:7
      volumes:
        - /github/home/.hunter:/github/home/.hunter
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5
      - uses: actions/cache@v2
        id: cache
        with:
          path: |
            /home/runner/.hunter
            /github/home/.hunter
            /home/runner/.hunter/_Base/Download/
            /github/home/.hunter/_Base/Download/
            deps/src
            ccache
          key: hunter-centos-v6-notest-${{ runner.temp }}-${{ github.base_ref }}-${{ hashFiles('.github/workflows/workflow.yml') }}
          restore-keys: |
            hunter-centos-v6-notest-${{ runner.temp }}-${{ github.base_ref }}-${{ hashFiles('.github/workflows/workflow.yml') }}
            hunter-centos-v6-notest-${{ runner.temp }}-${{ github.base_ref }}-
            hunter-centos-v6-notest-${{ runner.temp }}-
      - name: install CentOS dependencies
        run: |
          yum install -y epel-release centos-release-scl
          yum install -y git make gcc gcc-c++ glibc-static glibc-devel cmake3 ccache devtoolset-7 && source /opt/rh/devtoolset-7/enable
      - name: install rust language
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-06-17
          override: true
      - name: configure and compile
        run: |
          source /opt/rh/devtoolset-7/enable
          mkdir -p build && cd build
          cmake3 .. -DTESTS=ON
          make -j2
          CTEST_OUTPUT_ON_FAILURE=TRUE make test
